export const HANDLE_DASHBOARD = "HANDLE_DASHBOARD";
//
export const HANDLE_CATEGORY = "HANDLE_CATEGORY";
//
export const CLOSE_MODAL = "CLOSE_MODAL";
//
export const OFF_LOADING_MODAL = "OFF_LOADING_MODAL";
//
export const ON_LOADING_MODAL = "ON_LOADING_MODAL";
//
export const LOAD_LIST_CATEGORY = "LOAD_LIST_CATEGORY";
//
export const RESET_CATEGORY = "RESET_CATEGORY";
//
export const LOAD_PAGINATION = "LOAD_PAGINATION";
//
