export const HANDLE_DASHBOARD = "HANDLE_DASHBOARD";
//
export const HANDLE_CATEGORY = "HANDLE_CATEGORY";
//
export const CLOSE_MODAL = "CLOSE_MODAL";
//
export const OFF_LOADING_MODAL = "OFF_LOADING_MODAL";
//
export const ON_LOADING_MODAL = "ON_LOADING_MODAL";
//
export const LOAD_LIST_CATEGORY = "LOAD_LIST_CATEGORY";
//
export const RESET_CATEGORY = "RESET_CATEGORY";
//
export const LOAD_PAGINATION = "LOAD_PAGINATION";
//
export const OPEN_FORM_ADD = "OPEN_FORM_ADD";
//
export const OPEN_FORM_EDIT = "OPEN_FORM_EDIT";
//
export const ADD_ITEM_CHOOSE = "ADD_ITEM_CHOOSE";
//
export const REMOVE_ITEM_CHOOSE = "REMOVE_ITEM_CHOOSE";
